// Central Agency Datastore with translation content built-in
const AGENCY_DATA = [
    {
        id: "rmd",
        rank: 1,
        name: "RMD",
        logo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=88&h=88&fit=crop&crop=face",
        logoLarge: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=128&h=128&fit=crop&crop=face",
        rating: 4.9,
        reviews: 42,
        city: "Tangier",
        services: ["SEO", "Paid Ads", "Social Media", "Web Design", "Content Marketing"],
        budget: "15,000 MAD/mo",
        project: "50K-200K MAD",
        teamSize: "25-50",
        clientsServed: "150+",
        founded: "2018",
        address: "Avenue Mohammed VI, Bureau 45, Tangier 90000",
        email: "contact@rmd.ma",
        phone: "Available on request",
        website: "www.rmd.ma",
        stats: { speed: 98, vitals: "PASS", code: "99%" },
        en: {
            usp: "Digital growth partner for ambitious Moroccan brands.",
            description: "RMD delivers comprehensive digital marketing solutions with a focus on measurable ROI and long-term partnerships.",
            about: "<p>RMD (Réseau Marketing Digital) is a full-service digital marketing agency based in Tangier, Morocco. Founded in 2018, they have quickly established themselves as one of the country's premier growth partners for ambitious Moroccan brands looking to expand their digital presence.</p><p>Their team of 25+ specialists combines local market expertise with international best practices, delivering measurable ROI across SEO, paid media, social media, and web design. RMD has served over 150 clients across Morocco, from startups to established enterprises in industries including e-commerce, hospitality, fintech, and real estate.</p>",
            whyListed: [
                "<strong>Verified Reviews:</strong> 42 verified client reviews with an average rating of 4.9/5.0",
                "<strong>Portfolio Quality:</strong> Documented case studies showing 150%+ average ROI improvement",
                "<strong>Market Presence:</strong> 6+ years in business, 25+ team members, strong reputation",
                "<strong>Client Diversity:</strong> Proven track record across multiple corporate and startup clients"
            ],
            caseStudies: [
                { title: "Saas SEO Drive", tag: "SEO Audit" },
                { title: "Analytics Tracking Setup", tag: "Data Infra" },
                { title: "Google Ads Scale", tag: "PPC Search" }
            ],
            bestFor: "Full-service growth"
        },
        fr: {
            usp: "Partenaire de croissance digitale pour marques marocaines ambitieuses.",
            description: "RMD propose des solutions de marketing digital complètes axées sur un ROI mesurable et des partenariats durables.",
            about: "<p>RMD (Réseau Marketing Digital) est une agence de marketing digital intégrée basée à Tanger, au Maroc. Fondée en 2018, elle s'est rapidement imposée comme l'un des principaux partenaires de croissance pour les marques marocaines ambitieuses souhaitant développer leur présence en ligne.</p><p>Leur équipe de plus de 25 spécialistes allie expertise du marché local et meilleures pratiques internationales pour délivrer un ROI mesurable en SEO, publicité payante, réseaux sociaux et conception de sites web. RMD a accompagné plus de 150 clients à travers le Maroc, des startups aux grandes entreprises.</p>",
            whyListed: [
                "<strong>Avis Vérifiés :</strong> 42 avis clients vérifiés avec une note moyenne de 4,9/5,0",
                "<strong>Qualité du Portefeuille :</strong> Cas pratiques démontrant plus de 150% d'amélioration du ROI",
                "<strong>Présence sur le Marché :</strong> Plus de 6 ans d'activité, équipe de plus de 25 personnes",
                "<strong>Diversité Client :</strong> Expérience avérée auprès de nombreux secteurs et tailles d'entreprises"
            ],
            caseStudies: [
                { title: "Campagne SEO SaaS", tag: "Audit SEO" },
                { title: "Configuration Analytics", tag: "Data Infra" },
                { title: "Optimisation Google Ads", tag: "Publicité Search" }
            ],
            bestFor: "Croissance globale"
        }
    },
    {
        id: "pixagram",
        rank: 2,
        name: "Pixagram",
        logo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=88&h=88&fit=crop&crop=face",
        logoLarge: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=128&h=128&fit=crop&crop=face",
        rating: 4.8,
        reviews: 38,
        city: "Casablanca",
        services: ["Social Media", "Branding", "Content Marketing", "Paid Ads"],
        budget: "10,000 MAD/mo",
        project: "30K-150K MAD",
        teamSize: "15-25",
        clientsServed: "90+",
        founded: "2019",
        address: "Boulevard Anfa, Res. Yasmina, Casablanca 20000",
        email: "hello@pixagram.ma",
        phone: "Available on request",
        website: "www.pixagram.ma",
        stats: { speed: 95, vitals: "PASS", code: "96%" },
        en: {
            usp: "Creative digital agency specializing in social media and brand storytelling.",
            description: "Pixagram helps Moroccan brands build authentic connections with their audiences through visual brilliance.",
            about: "<p>Pixagram is a creative-first digital marketing agency headquartered in the economic heart of Morocco, Casablanca. Since our founding in 2019, we have focused on bridging the gap between brand storytelling and performance marketing.</p><p>We work with leading consumer brands, retail chains, and fast-growing startups to craft unique brand identities, execute viral social media campaigns, and drive sales through highly creative advertising. Our team consists of designers, copywriters, community managers, and media buyers who thrive on innovation and visual excellence.</p>",
            whyListed: [
                "<strong>Verified Reviews:</strong> 38 verified client reviews with an average rating of 4.8/5.0",
                "<strong>Branding Excellence:</strong> Vetted records for creative design and identity campaign execution",
                "<strong>Social Engagement:</strong> High benchmark engagement rates on client social channels",
                "<strong>Local Market Focus:</strong> Deep expertise in Moroccan consumer behavior and Darija dialect"
            ],
            caseStudies: [
                { title: "Creator Campaigns", tag: "Social Growth" },
                { title: "Visual Brand Refresh", tag: "Brand Design" },
                { title: "E-Commerce Media Buys", tag: "Social Ads" }
            ],
            bestFor: "Social & branding"
        },
        fr: {
            usp: "Agence digitale créative spécialisée en réseaux sociaux et image de marque.",
            description: "Pixagram aide les marques marocaines à créer des liens authentiques avec leurs audiences via la créativité visuelle.",
            about: "<p>Pixagram est une agence créative basée dans le cœur économique du Maroc, à Casablanca. Depuis notre création en 2019, nous combinons l'art du storytelling et la rigueur du marketing de performance.</p><p>Nous collaborons avec de grandes marques de consommation, des réseaux de distribution et des startups en pleine croissance pour créer des identités de marque mémorables et déployer des campagnes sociales virales.</p>",
            whyListed: [
                "<strong>Avis Vérifiés :</strong> 38 avis clients vérifiés avec une note moyenne de 4,8/5,0",
                "<strong>Excellence Créative :</strong> Reconnue pour son design innovant et ses campagnes d'image",
                "<strong>Engagement Social :</strong> Excellents taux d'engagement sur les réseaux clients",
                "<strong>Contexte Local :</strong> Maîtrise des codes culturels et de la Darija marocaine"
            ],
            caseStudies: [
                { title: "Campagnes d'Influence", tag: "Social Growth" },
                { title: "Refonte d'Identité Visuelle", tag: "Brand Design" },
                { title: "Publicités E-commerce", tag: "Social Ads" }
            ],
            bestFor: "Social & image"
        }
    },
    {
        id: "mediaboost",
        rank: 3,
        name: "MediaBoost",
        logo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=88&h=88&fit=crop&crop=face",
        logoLarge: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=128&h=128&fit=crop&crop=face",
        rating: 4.7,
        reviews: 31,
        city: "Rabat",
        services: ["Paid Ads", "SEO", "CRO", "Analytics"],
        budget: "12,000 MAD/mo",
        project: "40K-180K MAD",
        teamSize: "10-20",
        clientsServed: "75+",
        founded: "2020",
        address: "Avenue Allal Ben Abdellah, Agdal, Rabat 10000",
        email: "growth@mediaboost.ma",
        phone: "Available on request",
        website: "www.mediaboost.ma",
        stats: { speed: 91, vitals: "PASS", code: "94%" },
        en: {
            usp: "Performance-driven agency focused on paid acquisition and CRO.",
            description: "MediaBoost excels at scaling e-commerce brands through data-backed advertising and optimization strategies.",
            about: "<p>MediaBoost is Rabat's premier performance marketing agency, focusing on direct-response advertising and conversion rate optimization. Established in 2020, we have helped dozens of e-commerce brands, real estate developers, and service businesses maximize their digital ROI.</p><p>We do not focus on vanity metrics like likes or impressions; we focus on sales, leads, and revenue. Our methodology is built on continuous testing, deep data analysis, and advanced tracking configurations.</p>",
            whyListed: [
                "<strong>Verified Reviews:</strong> 31 verified client reviews with an average rating of 4.7/5.0",
                "<strong>E-commerce Scaling:</strong> Proven record of scaling Shopify and custom eCommerce setups in Morocco",
                "<strong>Analytics Audit:</strong> Expert setups for advanced tracking, attribution, and server-side configurations",
                "<strong>CRO Expertise:</strong> Clear frameworks that yield average conversion improvements of 20%+"
            ],
            caseStudies: [
                { title: "Media Buying Setups", tag: "Facebook Ads" },
                { title: "CRO Audit & Landings", tag: "Conversion Rate" },
                { title: "Attribution Tracking", tag: "Analytics Setup" }
            ],
            bestFor: "Paid acquisition"
        },
        fr: {
            usp: "Agence de performance axée sur l'acquisition payante et le CRO.",
            description: "MediaBoost excelle dans la croissance des marques e-commerce via la publicité et l'optimisation des conversions.",
            about: "<p>MediaBoost est l'agence de performance de référence à Rabat, spécialisée dans la publicité à réponse directe et l'optimisation des taux de conversion. Depuis 2020, nous aidons les sites e-commerce et les promoteurs immobiliers à maximiser leur ROI digital.</p>",
            whyListed: [
                "<strong>Avis Vérifiés :</strong> 31 avis clients vérifiés avec une note moyenne de 4,7/5,0",
                "<strong>Spécialisation E-commerce :</strong> Résultats démontrés sur Shopify et WooCommerce au Maroc",
                "<strong>Briques Analytics :</strong> Configuration experte du tracking et de l'attribution publicitaire",
                "<strong>Méthode CRO :</strong> Optimisation des pages d'atterrissage pour booster les ventes de +20%"
            ],
            caseStudies: [
                { title: "Campagnes Google & Meta", tag: "Facebook Ads" },
                { title: "Landing Pages & CRO", tag: "Conversion Rate" },
                { title: "Plan de Marquage Analytics", tag: "Analytics Setup" }
            ],
            bestFor: "Acquisition payante"
        }
    },
    {
        id: "digitalwave",
        rank: 4,
        name: "DigitalWave",
        logo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=88&h=88&fit=crop&crop=face",
        logoLarge: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=128&h=128&fit=crop&crop=face",
        rating: 4.6,
        reviews: 27,
        city: "Casablanca",
        services: ["Web Design", "SEO", "Branding"],
        budget: "20,000 MAD/mo",
        project: "60K-300K MAD",
        teamSize: "30-50",
        clientsServed: "120+",
        founded: "2017",
        address: "Boulevard Abdelmoumen, Casablanca 20000",
        email: "hello@digitalwave.ma",
        phone: "Available on request",
        website: "www.digitalwave.ma",
        stats: { speed: 89, vitals: "PASS", code: "90%" },
        en: {
            usp: "Full-service digital agency with strong custom web engineering.",
            description: "DigitalWave builds high-performance web solutions and integrates SEO campaigns to scale corporate brands.",
            about: "<p>DigitalWave is a tech-focused digital agency based in Casablanca. We specialize in custom web development, complex e-commerce builds, and integrated search engine optimization campaigns.</p><p>We believe that a high-converting website is the foundation of all digital marketing, and we build architectures that are fast, secure, and search-engine friendly. Our team of web engineers and digital marketers work together to build custom web experiences and scale their visibility across search engines.</p>",
            whyListed: [
                "<strong>Verified Reviews:</strong> 27 verified client reviews with an average rating of 4.6/5.0",
                "<strong>Engineering Quality:</strong> Superior custom code builds without bloated templates or plugins",
                "<strong>SEO Integration:</strong> Web designs engineered from day one for search engine crawling",
                "<strong>Industry Experience:</strong> 7+ years serving corporate brands and financial institutions in Morocco"
            ],
            caseStudies: [
                { title: "Custom Headless E-shop", tag: "Web Dev" },
                { title: "Corporate SEO Strategy", tag: "Organic Search" },
                { title: "Integrated Rebranding", tag: "Brand Launch" }
            ],
            bestFor: "Web & integrated"
        },
        fr: {
            usp: "Agence digitale globale avec une forte expertise en ingénierie web.",
            description: "DigitalWave conçoit des sites web ultra-performants et déploie des stratégies SEO globales pour les grandes marques.",
            about: "<p>DigitalWave est une agence digitale axée sur la technologie et basée à Casablanca. Nous sommes spécialisés dans le développement web sur mesure, les projets e-commerce complexes et les campagnes SEO intégrées.</p>",
            whyListed: [
                "<strong>Avis Vérifiés :</strong> 27 avis clients vérifiés avec une note moyenne de 4,6/5,0",
                "<strong>Qualité Technique :</strong> Développement sur mesure sans thèmes lourds ou plugins superflus",
                "<strong>SEO Tech :</strong> Sites optimisés dès la première ligne de code pour les moteurs de recherche",
                "<strong>Longévité :</strong> Plus de 7 ans d'expérience au service de grandes entreprises marocaines"
            ],
            caseStudies: [
                { title: "E-shop Headless Sur Mesure", tag: "Web Dev" },
                { title: "SEO Grand Compte", tag: "Organic Search" },
                { title: "Rebranding Institutionnel", tag: "Brand Launch" }
            ],
            bestFor: "Développement web & SEO"
        }
    },
    {
        id: "nexamedia",
        rank: 5,
        name: "NexaMedia",
        logo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=88&h=88&fit=crop&crop=face",
        logoLarge: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=128&h=128&fit=crop&crop=face",
        rating: 4.5,
        reviews: 22,
        city: "Marrakech",
        services: ["Content Marketing", "SEO", "Social Media"],
        budget: "8,000 MAD/mo",
        project: "25K-100K MAD",
        teamSize: "10-15",
        clientsServed: "60+",
        founded: "2021",
        address: "Avenue Mohammed V, Gueliz, Marrakech 40000",
        email: "hello@nexamedia.ma",
        phone: "Available on request",
        website: "www.nexamedia.ma",
        stats: { speed: 92, vitals: "PASS", code: "93%" },
        en: {
            usp: "Content-first agency building search authority and PR.",
            description: "NexaMedia helps tourism, hospitality, and local brands rank through editorial excellence and local SEO.",
            about: "<p>NexaMedia is Marrakech's leading content marketing and search engine agency. We believe content is the ultimate asset for building trust and organic visibility.</p><p>We help hotel groups, real estate developments, and local businesses craft compelling blog content, optimize for local search engines, and manage their social media communities. We combine journalistic storytelling with performance optimization to ensure your content ranks and converts.</p>",
            whyListed: [
                "<strong>Verified Reviews:</strong> 22 verified client reviews with an average rating of 4.5/5.0",
                "<strong>Editorial Quality:</strong> Team of professional writers producing bilingual SEO content",
                "<strong>Hospitality Playbooks:</strong> Specialized digital playbooks for hotels, riads, and travel operators",
                "<strong>Local SEO Focus:</strong> Vetted results optimizing Google Maps and local search listings"
            ],
            caseStudies: [
                { title: "Hotel Blog Strategy", tag: "Content Marketing" },
                { title: "Local Map Optimization", tag: "Local SEO" },
                { title: "Community Launch", tag: "Social Media" }
            ],
            bestFor: "Content & SEO"
        },
        fr: {
            usp: "Agence éditoriale spécialisée dans le contenu et les relations presse.",
            description: "NexaMedia aide les acteurs du tourisme et de l'immobilier à rayonner via le contenu de marque et le SEO local.",
            about: "<p>NexaMedia est l'agence leader en marketing de contenu à Marrakech. Nous pensons que le contenu est l'actif principal pour asseoir la confiance des clients et booster la visibilité naturelle.</p>",
            whyListed: [
                "<strong>Avis Vérifiés :</strong> 22 avis clients vérifiés avec une note moyenne de 4,5/5,0",
                "<strong>Qualité Éditoriale :</strong> Rédacteurs professionnels produisant du contenu SEO de haut niveau",
                "<strong>Secteur Tourisme :</strong> Expertise reconnue auprès des riads, hôtels et resorts",
                "<strong>SEO Local :</strong> Optimisation poussée de Google Maps et fiches d'établissement"
            ],
            caseStudies: [
                { title: "Blog d'Hôtel de Luxe", tag: "Content Marketing" },
                { title: "Visibilité Maps & Local", tag: "Local SEO" },
                { title: "Gestion Communautaire", tag: "Social Media" }
            ],
            bestFor: "Contenu & SEO local"
        }
    },
    {
        id: "saharadigital",
        rank: 6,
        name: "Sahara Digital",
        logo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=88&h=88&fit=crop&crop=face",
        logoLarge: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=128&h=128&fit=crop&crop=face",
        rating: 4.4,
        reviews: 19,
        city: "Agadir",
        services: ["Social Media", "Web Design", "Branding"],
        budget: "8,000 MAD/mo",
        project: "20K-80K MAD",
        teamSize: "8-12",
        clientsServed: "45+",
        founded: "2021",
        address: "Avenue Hassan II, Agadir 80000",
        email: "contact@saharadigital.ma",
        phone: "Available on request",
        website: "www.saharadigital.ma",
        stats: { speed: 88, vitals: "PASS", code: "91%" },
        en: {
            usp: "Southern Morocco's leading agency for tourism & hospitality.",
            description: "Sahara Digital builds responsive web platforms and local campaigns reflecting the authentic spirit of the Souss region.",
            about: "<p>Sahara Digital is the leading digital agency in southern Morocco, based in Agadir. We serve the growing hospitality, surf tourism, and agricultural export business ecosystem of Souss-Massa.</p><p>Our team specializes in branding, high-performing websites, and localized social media campaigns that attract domestic and international clients alike. We build responsive web platforms and manage social narratives that reflect the authentic spirit of the region.</p>",
            whyListed: [
                "<strong>Verified Reviews:</strong> 19 verified client reviews with an average rating of 4.4/5.0",
                "<strong>Regional Leader:</strong> Prime provider for Souss-Massa hotels, surfing camps, and cooperatives",
                "<strong>Multilingual Focus:</strong> Capability to launch campaigns in French, English, and German",
                "<strong>Agile Execution:</strong> Highly responsive, lean, and collaborative team structure"
            ],
            caseStudies: [
                { title: "Surf Camp Branding", tag: "Identity & Social" },
                { title: "Resort Web Design", tag: "E-commerce Web" },
                { title: "Tourism Promo Ads", tag: "Paid Social" }
            ],
            bestFor: "Tourism & local branding"
        },
        fr: {
            usp: "Agence leader du Sud Marocain pour le tourisme et l'hôtellerie.",
            description: "Sahara Digital développe des sites web modernes et des campagnes locales incarnant l'esprit de la région Souss.",
            about: "<p>Sahara Digital est l'agence digitale de référence dans le sud du Maroc, installée à Agadir. Nous accompagnons l'écosystème touristique (surf, riads) et agroalimentaire de Souss-Massa.</p>",
            whyListed: [
                "<strong>Avis Vérifiés :</strong> 19 avis clients vérifiés avec une note moyenne de 4,4/5,0",
                "<strong>Ancrage Régional :</strong> Agence privilégiée par les acteurs touristiques régionaux",
                "<strong>Campagnes Multilingues :</strong> Contenus créés en français, anglais et allemand",
                "<strong>Équipe Agile :</strong> Structure réactive, flexible et proche de ses clients"
            ],
            caseStudies: [
                { title: "Branding Club de Surf", tag: "Identity & Social" },
                { title: "Site Web Resort Touristique", tag: "E-commerce Web" },
                { title: "Campagnes d'Acquisition Social", tag: "Paid Social" }
            ],
            bestFor: "Tourisme & image de marque"
        }
    }
];

// Dictionary of Bilingual Translations
const TRANSLATIONS = {
    en: {
        navHome: "home",
        navAbout: "about",
        navAgencies: "directory",
        navRankings: "rankings",
        navMethodology: "methodology",
        navContact: "contact",
        navSearch: "search",
        heroTitle: "Find the <span class='hero-focus-word'>best</span> digital marketing agencies in <span class='hero-location-word'>Morocco</span>",
        heroLede: "Use independent research to evaluate digital agencies by technical SEO signals, client evidence, service fit, and transparent review standards.",
        heroBrowseBtn: "Find my ideal agency",
        heroRankingsBtn: "Get my agency listed",
        lblService: "Service",
        lblCity: "City",
        lblRating: "Rating",
        lblSort: "Sort by",
        lblSearch: "Search",
        btnSearch: "Search research",
        heroPillClient: "150+ agencies evaluated",
        heroPillAgency: "100% editorial ranking",
        homeCtaLabel: "Matchmaker",
        homeCtaTitle: "Ready to find the right digital agency?",
        homeCtaDesc: "Skip the sales pitches. Match your project in 2 minutes and let our independent audits identify the perfect partner for your growth goals.",
        homeCtaPrimaryBtn: "Launch Matchmaker",
        homeCtaSecondaryBtn: "Explore Directory",
        homeAgencyCtaLabel: "Agencies",
        homeAgencyCtaTitle: "Your agency deserves to be in the rankings.",
        homeAgencyCtaDesc: "Submit your agency to our editorial team. Evaluated on 4 objective criteria. 0 placement fee. Result published in 3–5 business days.",
        homeAgencyCtaBtn: "Submit my agency",
        blogKicker: "Editorial analysis",
        blogTitle: "Digital Agency\nIntelligence",
        blogLede: "Technical notes on Moroccan agencies, organic visibility, Core Web Vitals, and the evidence that separates real SEO operators from polished sales pitches.",
        blogTopicAll: "All",
        blogTopicRanking: "Rankings",
        blogTopicGuide: "Guides",
        blogTopicSeo: "SEO Audits",
        blogTopicComparison: "Comparisons",
        blogArticlesLabel: "articles",
        blogProposeArticle: "Pitch an article",
        blogNewsletterKicker: "Newsletter · Free",
        blogNewsletterTitle: "Get our analyses straight to your inbox.",
        blogNewsletterDesc: "Every two weeks: one agency audit, one SEO signal to watch, one resource selection for founders and marketing directors.",
        blogNewsletterBtn: "Subscribe",
        blogNewsletterMicro: "No spam · Unsubscribe in 1 click",
        quickAboutTitle: "About the project",
        quickAboutText: "Why this resource exists.",
        quickBlogTitle: "Read the blog",
        quickBlogText: "Guides and comparisons.",
        quickMethodTitle: "Methodology",
        quickMethodText: "How reviews are evaluated.",
        quickContactTitle: "Contact us",
        quickContactText: "Corrections and questions.",
        optAllServices: "All Services",
        optAllCities: "All Cities",
        optAnyRating: "Any Rating",
        opt45Stars: "4.5+ Stars",
        opt40Stars: "4.0+ Stars",
        optSortRank: "Rank: High to Low",
        optSortRating: "Rating: High to Low",
        optSortReviews: "Reviews: Most to Least",
        challengeLabel: "The Challenge",
        challengeTitle: "Most agency decisions start with <span class='challenge-focus-word'>weak evidence</span> and end with <span class='challenge-time-word'>wasted budget</span>.",
        challengeDesc: "Agency websites often look polished, but buyers still need proof: technical execution, search visibility, client outcomes, and a clear method for comparing one team against another.",
        challengeBullet1Title: "Claims without proof",
        challengeBullet1Text: "Many agencies say they are market leaders without showing crawl, ranking, or client evidence.",
        challengeBullet2Title: "Testimonials without context",
        challengeBullet2Text: "Reviews are useful only when they connect to project scope, budget, and measurable outcomes.",
        challengeBullet3Title: "SEO quality is hard to see",
        challengeBullet3Text: "Poor technical foundations can hide behind strong branding until traffic stalls.",
        challengeQuote: "We burned through two agencies and 200,000 dirhams before we found one that actually delivered. If this directory had existed, we would have saved six months.",
        challengeQuoteVerified: "Verified review",
        challengeQuoteScope: "Project: SEO & Paid Ads",
        approachLabel: "Our Approach",
        approachTitle: "A <span class='approach-focus-word'>clearer way</span> to <span class='approach-action-word'>evaluate</span> agencies.",
        approachDesc: "We turn scattered agency claims into structured research signals.",
        approachPoint1Title: "Technical Review",
        approachPoint1Text: "We look at portfolio quality, SEO foundations, site performance, service focus, and whether claims are supported by visible evidence.",
        approachPoint2Title: "Evidence-Based Scoring",
        approachPoint2Text: "Agencies are compared with consistent criteria rather than paid placement, vague reputation, or sales copy alone.",
        approachPoint3Title: "Buyer-Ready Notes",
        approachPoint3Text: "The goal is to help teams ask better questions, shortlist faster, and avoid partners whose execution does not match the pitch.",
        stat1Label: "Agencies researched and listed",
        stat2Label: "Client reviews verified by our team",
        stat3Label: "Moroccan cities covered",
        stat4Label: "Paid placements or promoted ranks",
        reviewsKicker: "Verified client outcomes",
        reviewsTitle: "What teams say after choosing through Agence Marketing Digital",
        reviewsDesc: "Real selection stories from Moroccan teams that used verified profiles, audit notes, and client evidence before contacting an agency.",
        reviewsMetric1: "Avg. verified rating",
        reviewsMetric2: "Would shortlist again",
        reviewsMetric3: "Reviews checked",
        reviewsHired: "Hired",
        reviewsProject: "Project",
        reviewsResult: "Result",
        review1Quote: "\"The RMD profile showed exactly what we needed: SEO proof, budget range, and verified client comments. We shortlisted them in one afternoon and saw organic leads climb 38% after the audit fixes.\"",
        review1Role: "Marketing Lead - Dakhla Travel Co.",
        review1Project: "Technical SEO audit and local landing pages",
        review1Result: "Organic leads +38% in 10 weeks",
        review2Quote: "\"Pixagram's profile made the decision feel lower-risk. The portfolio notes matched our category, and their team rebuilt our social launch system without pushing services we did not need.\"",
        review2Role: "Co-founder - Casa Homeware",
        review2Project: "Brand refresh and social commerce launch",
        review2Result: "Instagram sales +44% after launch",
        review3Quote: "\"We compared three paid media agencies and chose MediaBoost because the review evidence was specific. Their tracking cleanup finally showed which campaigns were producing qualified leads.\"",
        review3Role: "Growth Manager - Rabat Fintech Lab",
        review3Project: "Paid acquisition tracking and CRO sprint",
        review3Result: "Cost per qualified lead down 31%",
        picksLabel: "Editor's Picks",
        picksTitle: "Agencies with the strongest evidence signals.",
        picksLink: "Review the methodology",
        specialtiesLabel: "Specialties",
        specialtiesTitle: "Research by marketing problem.",
        specialtiesLink: "SEO research",
        servicePaidAds: "Paid Ads",
        serviceSocial: "Social Media",
        serviceWeb: "Web Design",
        serviceBranding: "Branding",
        serviceContent: "Content Marketing",
        serviceGroupSearch: "Search & Growth",
        serviceGroupBrand: "Brand & Social",
        serviceGroupWeb: "Web & Conversion",
        serviceGroupTopRanked: "Evaluation standards",
        serviceGroupStorytelling: "Content Strategy",
        serviceGroupLaunchCampaigns: "Launch Campaigns",
        serviceGroupGuides: "Selection guides",
        serviceGroupLandingPages: "Landing Pages",
        serviceGroupEcommerce: "E-commerce",
        serviceGroupTechnicalSeo: "Technical SEO",
        serviceGroupCRO: "Conversion audits",
        serviceCompare: "Compare specialists",
        serviceSeoDesc: "Find agencies for technical audits, local rankings, content planning, and search growth.",
        servicePaidAdsDesc: "Shortlist teams for Google Ads, Meta campaigns, tracking cleanup, and lead quality.",
        serviceSocialDesc: "Compare creators, community teams, and campaign partners with Moroccan audience context.",
        serviceWebDesc: "Review studios for fast landing pages, conversion flows, ecommerce, and redesign projects.",
        serviceBrandingDesc: "Find partners for positioning, identity systems, campaign concepts, and launch messaging.",
        serviceContentDesc: "Shortlist teams for editorial calendars, SEO articles, email flows, and authority building.",
        trustLabel: "Independence",
        trustTitle: "Research should not be influenced by paid placement.",
        trustDesc: "Our editorial positioning is simple: compare agencies through visible evidence, consistent criteria, and a published methodology instead of sponsorship or referral incentives.",
        trustPoint1: "Every review is email-verified and cross-checked",
        trustPoint2: "Portfolio audits by industry-experienced editors",
        trustPoint3: "Quarterly re-evaluation of all listed agencies",
        trustPoint4: "No referral fees, commissions, or paid placement",
        trustLink: "See the evaluation method",
        guidesLabel: "Editorial",
        guidesTitle: "SEO-led agency research.",
        guidesLink: "All articles",
        badgeRanking: "Ranking",
        badgeGuide: "Guide",
        badgeComparison: "Comparison",
        guide1Title: "Morocco SEO Agency Audit: Top Performers",
        guide1Desc: "A technical shortlist based on crawl health, Core Web Vitals, indexation discipline, content systems, and proof of search-led growth.",
        guide2Title: "Casablanca SEO Agencies: Technical Shortlist",
        guide2Desc: "Which Casablanca teams show real SEO craft: fast builds, clean architecture, local search coverage, and measurable organic acquisition.",
        guide3Title: "Social Agencies Through an SEO Lens",
        guide3Desc: "A comparison of social teams by brand demand, content velocity, discoverability, creator relevance, and downstream search impact.",
        guideDateJune: "Updated June 2026",
        guideDateMay: "Updated May 2026",
        guideDateApril: "Updated April 2026",
        dirLabel: "Directory",
        dirTitle: "Digital Marketing Agencies",
        dirDesc: "Browse and compare agencies by city, service, and expertise.",
        showingTxt: "Showing",
        agenciesTxt: "agencies",
        searchPlaceholder: "Agency name...",
        viewProfileBtn: "View Profile",
        visitWebsiteBtn: "Visit Website",
        profileVisitWebsite: "Visit Website",
        profileContact: "Contact",
        profileAuditTitle: "technical audit telemetry",
        profileSpeed: "pagespeed score",
        profileVitals: "core web vitals",
        profileCode: "code cleanliness index",
        profileGoogleCWV: "Vetted via Lighthouse API",
        profileAboutHeading: "About",
        profileServicesHeading: "Services",
        profilePortfolioHeading: "Portfolio Highlights",
        profileWhyHeading: "Why",
        profileWhyHeadingEnd: "is Listed",
        profileContactHeading: "Direct Details",
        profileSendMessageBtn: "Send Message",
        profileStatsHeading: "Quick Stats",
        profileStatFounded: "Founded",
        profileStatTeam: "Team Size",
        profileStatClients: "Clients Served",
        profileStatProject: "Avg. Project",
        profileStatBudget: "Min. Budget",
        profileSimilarHeading: "Similar Agencies",
        rankBadgeLabel: "2026 Ranking",
        rankTitle: "Top Digital Marketing Agencies in Morocco",
        rankDesc: "After evaluating 150+ agencies across Morocco, our independent research team has identified the top performers based on verified client reviews, portfolio quality, market presence, and team expertise.",
        rankDate: "Updated June 2026",
        rankVerified: "Research verified",
        rankTableTitle: "Quick Overview",
        rankBottomTitle: "How We Chose These Agencies",
        rankBottomDesc: "Our ranking methodology is transparent and independent. We do not accept payment for placement. Agencies are evaluated on four core criteria:",
        rankCrit1: "1. Verified Client Reviews",
        rankCrit1Desc: "We collect and verify reviews from real clients, weighted by project complexity and budget.",
        rankCrit2: "2. Portfolio Quality",
        rankCrit2Desc: "Our team evaluates case studies, work samples, and measurable results demonstrated.",
        rankCrit3: "3. Market Presence",
        rankCrit3Desc: "Years in business, team size, industry recognition, and thought leadership.",
        rankCrit4: "4. Service Breadth",
        rankCrit4Desc: "Range of services offered, specialization depth, and cross-channel expertise.",
        faqTitle: "Frequently Asked Questions",
        faqRankQ1: "How often are these rankings updated?",
        faqRankA1: "Our rankings are updated quarterly. We continuously collect new reviews, monitor agency performance, and reassess portfolios. Major updates are published in March, June, September, and December each year.",
        faqRankQ2: "Can agencies pay to be ranked higher?",
        faqRankA2: "No. Our rankings are 100% independent and based solely on merit. Agencies can purchase enhanced profile features, but this never influences their ranking position. We maintain strict editorial independence.",
        faqRankQ3: "How do you verify client reviews?",
        faqRankA3: "We verify reviews through a multi-step process: email verification of the reviewer, LinkedIn profile confirmation, project documentation review, and direct follow-up calls for high-value projects. Fake reviews are removed.",
        faqRankQ4: "What budget should I expect for a top-ranked agency?",
        faqRankA4: "Top-ranked agencies typically require minimum monthly retainers starting at 15,000-25,000 MAD for ongoing services. Project-based work (like website design) usually starts at 50,000 MAD.",
        methTitle: "Our Evaluation <span class='quiet'>Standards.</span>",
        methDesc: "How we research, evaluate, and rank digital marketing agencies in Morocco. Updated June 2026.",
        methFlowBtn: "See the flow",
        methFlowEyebrow: "01 / Verification Flow",
        methFlowTitle: "Four gates. One standard.",
        methFlowDesc: "The same sequence is applied to every listed agency, whether they applied or were discovered by the editorial team.",
        methStage1Tag1: "2+ years",
        methStage1Tag2: "registered",
        methStage1Tag3: "5+ projects",
        methStage2Tag1: "ROI proof",
        methStage2Tag2: "SEO",
        methStage2Tag3: "mobile",
        methStage3Tag1: "email",
        methStage3Tag2: "LinkedIn",
        methStage3Tag3: "phone",
        methStage4Tag1: "35%",
        methStage4Tag2: "30%",
        methStage4Tag3: "20%",
        methStage4Tag4: "15%",
        
        methEvidenceEyebrow: "02 / Evidence Map",
        methEvidenceTitle: "Claims need receipts.",
        methEvidenceLegalTitle: "Legal",
        methEvidenceLegalDesc: "Business registration, continuity of operation, and contact traceability are checked before deeper scoring starts.",
        methEvidenceWorkTitle: "Work",
        methEvidenceWorkDesc: "Case studies are reviewed for actual deliverables, technical execution, mobile quality, SEO foundations, and measurable outcomes.",
        methEvidenceClientTitle: "Client",
        methEvidenceClientDesc: "Reviews are tied to real people, real project relationships, and direct confirmation for larger budgets.",
        methEvidenceDataTitle: "Data",
        methEvidenceDataDesc: "Scores are weighted so a loud brand cannot outrank a stronger agency on reputation alone.",
        
        methAfterEyebrow: "03 / After Listing",
        methAfterTitle: "We keep checking agencies.",
        methAfterDesc: "A ranked agency can go up, go down, or be removed if new proof shows the quality changed.",
        methAfterStep1Title: "Every 3 months",
        methAfterStep1Desc: "We check listed agencies again so old rankings do not stay there forever.",
        methAfterStep2Title: "Bad client reports",
        methAfterStep2Desc: "Real complaints from verified clients trigger a manual review.",
        methAfterStep3Title: "Outdated proof",
        methAfterStep3Desc: "Weak portfolio work, legal issues, or unsupported claims lower trust.",
        methAfterStep4Title: "Fake reviews",
        methAfterStep4Desc: "Trying to manipulate reviews or rankings can remove the agency.",
        methOverviewHeading: "Overview",
        methOverviewP1: "Our evaluation process is designed to be comprehensive, consistent, and fair. Every agency in our directory has been through the same research protocol, regardless of whether they applied for listing or were discovered by our editorial team.",
        methOverviewP2: "The process takes 2-4 weeks per agency and involves four stages: initial screening, portfolio audit, client verification, and final scoring. Agencies that fail any stage are not listed.",
        methStep1Title: "Initial Screening",
        methStep1Desc: "Before any deep research begins, we verify that an agency meets our minimum eligibility criteria:",
        methStep1Bullet1: "Minimum 2 years in continuous business operation",
        methStep1Bullet2: "Professional website with clear service descriptions",
        methStep1Bullet3: "Valid business registration in Morocco",
        methStep1Bullet4: "At least 5 verifiable client projects in portfolio",
        methStep2Title: "Portfolio Audit",
        methStep2Desc: "Our editorial team conducts a detailed review of the agency's publicly available work and privately submitted case studies:",
        methStep2Bullet1: "Quality of design and creative execution",
        methStep2Bullet2: "Evidence of measurable results (ROI, traffic, conversions)",
        methStep2Bullet3: "Technical competence (site speed, SEO, mobile optimization)",
        methStep3Title: "Client Verification",
        methStep3Desc: "This is the most critical stage. We contact current and former clients directly to verify the agency's claims:",
        methStep3Bullet1: "Email verification of reviewer identity and relationship to agency",
        methStep3Bullet2: "LinkedIn profile confirmation of reviewer position",
        methStep3Bullet3: "Direct phone interviews for projects over 50,000 MAD",
        methStep4Title: "Final Scoring",
        methStep4Desc: "Agencies that pass all three stages receive a composite score based on four weighted criteria:",
        methCrit1: "Verified Client Reviews",
        methCrit2: "Portfolio Quality",
        methCrit3: "Market Presence",
        methCrit4: "Service Breadth",
        contactTitle: "Contact Agence Marketing Digital",
        contactDesc: "Questions about agency data, corrections, listing reviews, or editorial research? Send the details and our editorial team will follow up.",
        contactFormHeading: "Send a Message",
        contactFirstName: "First Name",
        contactLastName: "Last Name",
        contactEmail: "Email",
        contactSubject: "Subject",
        contactMessage: "Message",
        contactSubmitBtn: "Send Message",
        holderFirstName: "Your first name",
        holderLastName: "Your last name",
        holderEmail: "you@company.com",
        holderMessage: "How can we help you?",
        contactExploreEyebrow: "Prefer to explore first?",
        contactExploreTitle: "Read the research before you send a message.",
        contactExploreDesc: "Use the blog and methodology pages for context. Keep the contact form for corrections, listing requests, and direct questions.",
        contactExploreDirectory: "Read the blog",
        contactExploreRankings: "See methodology",
        subjectOption1: "General Inquiry",
        subjectOption2: "Get My Agency Listed",
        subjectOption3: "Report an Issue",
        subjectOption4: "Partnership Opportunity",
        contactPathListingTitle: "Agency listing review",
        contactPathListingText: "Send your agency name, website, city, services, and 2-3 client references so our editors can assess fit.",
        contactPathCorrectionTitle: "Data correction",
        contactPathCorrectionText: "Flag outdated ratings, wrong services, contact details, or portfolio claims. Include the profile URL when possible.",
        contactPathBuyerTitle: "Buyer shortlist help",
        contactPathBuyerText: "Tell us your city, budget, timeline, and required services. We will point you toward the most relevant research or guide.",
        contactResponseTitle: "What happens next",
        contactResponse1: "Editorial requests are reviewed before any profile changes are published.",
        contactResponse2: "Listing requests need evidence, not sales claims.",
        contactResponse3: "Most useful messages include links, numbers, and project context.",
        contactInfoTitle: "Contact Information",
        contactOfficeTitle: "Main Office",
        officeCity: "Casablanca, Morocco",
        footerDesc: "Independent research on digital marketing agencies in Morocco. Objective reviews, practical guides, and no paid influence.",
        footerExploreHeading: "Explore",
        footerResourcesHeading: "Resources",
        footerDirHeading: "Directory",
        footerLinkAll: "All Agencies",
        footerLinkCity: "By City",
        footerLinkService: "By Service",
        footerCitiesHeading: "Cities",
        footerCompanyHeading: "Company",
        footerLegalHeading: "Legal",
        footerLinkPrivacy: "Privacy Policy",
        footerLinkTerms: "Terms of Service",
        palettePlaceholder: "Search agencies, pages, cities...",
        blogTitle: "SEO Agency Intelligence",
        blogLede: "Technical notes on Moroccan agencies, search visibility, crawl quality, content depth, Core Web Vitals, and the evidence that separates real SEO operators from polished sales decks.",
        navBlog: "blog",
        aboutEyebrow: "About",
        aboutTitle: "Independent agency <span class='quiet'>research.</span>",
        aboutLead: "Agence Marketing Digital helps Moroccan teams understand the agency market with clear editorial standards, practical guides, and transparent research notes.",
        aboutMissionTitle: "What we do",
        aboutMissionText: "We review agency claims, explain selection criteria, and publish buyer-focused guidance so companies can ask sharper questions before choosing a partner.",
        aboutIndependenceTitle: "How we stay independent",
        aboutIndependenceText: "Our editorial process is separated from commercial requests. We do not sell ranking positions, and corrections are reviewed against evidence before publication.",
        aboutAudienceTitle: "Who it is for",
        aboutAudienceText: "The site is built for founders, marketing leads, and operators who need a calmer way to evaluate SEO, paid media, social, web, and content partners in Morocco.",
        aboutCtaEyebrow: "Process & Listing",
        aboutCtaTitle: "Want to understand the review process?",
        aboutCtaText: "Read the methodology for the criteria behind our research, or contact the editorial team with corrections and listing requests.",
        aboutMethodologyCta: "Read methodology",
        aboutContactCta: "Contact us",
        backToInsights: "back to insights",
        readTime: "min read",
        postedLabel: "on",
        authorLabel: "by",
        navCharter: "Editorial Charter",
        charterTitle: "Editorial Charter & Review Standards",
        charterSubtitle: "directory standards & trust signals",
        charterDesc: "The public standards behind our directory experience: how we present agency data, trust signals, review states, and ranking evidence consistently.",
        charterSec1: "01 · color tokens (oklch system)",
        charterSec2: "02 · typography families & scale",
        charterSec3: "03 · spacing scale values",
        charterSec4: "04 · interface components",
        charterSec5: "05 · directory card component spec",
        swatchBrandTitle: "electric cobalt",
        swatchBrandDesc: "Primary accent color, buttons, highlighted state tags, rank badges, hover underlines.",
        swatchPaperTitle: "paper base",
        swatchPaperDesc: "Core viewport background. Clean cool-grey tinted off-white.",
        swatchCardTitle: "paper card",
        swatchCardDesc: "Card backgrounds, inline dropdown triggers, header navigation bar background.",
        swatchGraphiteTitle: "dark graphite",
        swatchGraphiteDesc: "High contrast dark bands, statistics panels, matchmaking CTAs, footer widgets.",
        swatchInkTitle: "primary ink",
        swatchInkDesc: "Headings, titles, high contrast UI details, card ranks.",
        swatchMutedTitle: "muted ink",
        swatchMutedDesc: "Body copy, standard description labels, search placeholders.",
        swatchSuccessTitle: "audit success",
        swatchSuccessDesc: "Diagnostic green status badges, pulsing indicators, audit verification passes.",
        swatchBorderTitle: "hairline rule",
        swatchBorderDesc: "Clean dividers, layout hairline grids, panel borders.",
        typeDisplayTitle: "Display Title (Space Grotesk Bold)",
        typeH1Title: "Header H1 (Space Grotesk)",
        typeH2Title: "Section H2 (Space Grotesk)",
        typeH3Title: "Card H3 (Space Grotesk)",
        typeBodyTitle: "General Body (Inter)",
        typeMonoTitle: "Monospace label (JetBrains Mono)",
        compButtonsTitle: "buttons & micro badges",
        compTerminalTitle: "interactive terminal mockup",
        compBrandingTitle: "branding wordmark",
        compBrandingDesc: "A text-only wordmark using strong weight contrast and a cobalt accent on Marketing.",
        compBtnPrimary: "primary button",
        compBtnSoft: "soft button",
        compBadgeVerified: "verified status",
        compBadgeRating: "rating pill",
        compBadgeRank: "rank badge",
        compBadgeTag: "featured tag",
        cardSpecTitle: "Directory Card Spec",
        cardSpecDesc: "High-fidelity mock visual card detailing layout alignment, custom buttons, verified tags, and star-rating structures.",
        ctaMatchmaker: "Find My Agency",
        editorialHeading: "Editorial Insights",
        dirLabel: "Directory",
        dirTitle: "Digital Marketing Agencies",
        dirDesc: "Browse and compare agencies by city, service, and expertise.",
        rankBadgeLabel: "2026 Ranking",
        rankTitle: "Top Digital Marketing Agencies in Morocco",
        rankDesc: "After evaluating 150+ agencies across Morocco, our independent research team has identified the top performers based on verified client reviews, portfolio quality, market presence, and team expertise.",
        footerCitiesHeading: "Cities",
        footerResourcesHeading: "Resources",
        footerLegalHeading: "Legal",
        showingTxt: "Showing",
        agenciesTxt: "agencies",
        viewProfileBtn: "View Profile",
        searchPlaceholder: "Agency name...",
        backToInsights: "back to insights",
        matchmakerStep1: "What service do you need?",
        matchmakerStep2: "What is your city?",
        matchmakerStep3: "What is your monthly budget?",
        matchmakerStep4: "Tell us about your project"
    },
    fr: {
        navHome: "accueil",
        navAbout: "a propos",
        navAgencies: "annuaire",
        navRankings: "classements",
        navMethodology: "méthodologie",
        navContact: "contact",
        navSearch: "rechercher",
        heroTitle: "Trouvez les <span class='hero-focus-word'>meilleures</span> agences de marketing digital au <span class='hero-location-word'>Maroc</span>",
        heroLede: "Explorez des recherches fiables sur les agences digitales marocaines, des guides pratiques et notre processus editorial transparent.",
        heroBrowseBtn: "Trouver mon agence idéale",
        heroRankingsBtn: "Faire référencer mon agence",
        lblService: "Service",
        lblCity: "Ville",
        lblRating: "Note",
        lblSort: "Trier par",
        lblSearch: "Recherche",
        btnSearch: "Rechercher",
        heroPillClient: "150+ agences évaluées",
        heroPillAgency: "Référencement 100% éditorial",
        homeCtaLabel: "Matchmaker",
        homeCtaTitle: "Prêt à trouver la bonne agence digitale ?",
        homeCtaDesc: "Oubliez les argumentaires commerciaux. Décrivez votre projet en 2 minutes et laissez nos audits indépendants identifier le partenaire idéal pour votre croissance.",
        homeCtaPrimaryBtn: "Lancer le Matchmaker",
        homeCtaSecondaryBtn: "Explorer l'annuaire",
        homeAgencyCtaLabel: "Agences",
        homeAgencyCtaTitle: "Votre agence mérite d'être dans le classement.",
        homeAgencyCtaDesc: "Soumettez votre agence à notre équipe éditoriale. Évaluation sur 4 critères objectifs. 0 frais de placement. Résultat publié en 3 à 5 jours ouvrés.",
        homeAgencyCtaBtn: "Soumettre mon agence",
        blogKicker: "Analyses éditoriales",
        blogTitle: "Intelligence\nAgences Digitales",
        blogLede: "Notes techniques sur les agences marocaines, la visibilité organique, Core Web Vitals, et les preuves qui séparent les vrais opérateurs SEO des argumentaires commerciaux polis.",
        blogTopicAll: "Tout voir",
        blogTopicRanking: "Classements",
        blogTopicGuide: "Guides",
        blogTopicSeo: "Audits SEO",
        blogTopicComparison: "Comparatifs",
        blogArticlesLabel: "articles",
        blogProposeArticle: "Proposer un article",
        blogNewsletterKicker: "Newsletter · Gratuite",
        blogNewsletterTitle: "Recevez nos analyses directement dans votre boîte mail.",
        blogNewsletterDesc: "Chaque quinzaine : un audit d'agence, un signal SEO à surveiller, une sélection de ressources utiles pour les fondateurs et directeurs marketing.",
        blogNewsletterBtn: "S'abonner",
        blogNewsletterMicro: "Aucun spam · Désabonnement en 1 clic",
        quickAboutTitle: "A propos du projet",
        quickAboutText: "Pourquoi cette ressource existe.",
        quickBlogTitle: "Lire le blog",
        quickBlogText: "Guides et comparatifs.",
        quickMethodTitle: "Methodologie",
        quickMethodText: "Comment les avis sont evalues.",
        quickContactTitle: "Nous contacter",
        quickContactText: "Corrections et questions.",
        optAllServices: "Tous les Services",
        optAllCities: "Toutes les Villes",
        optAnyRating: "Toutes les Notes",
        opt45Stars: "4.5+ Étoiles",
        opt40Stars: "4.0+ Étoiles",
        optSortRank: "Rang : Haut à Bas",
        optSortRating: "Note : Haut à Bas",
        optSortReviews: "Avis : Plus au Moins",
        challengeLabel: "Le Défi",
        challengeTitle: "La plupart des entreprises choisissent la <span class='challenge-focus-word'>mauvaise agence</span> en <span class='challenge-time-word'>48 heures</span>.",
        challengeDesc: "Le marché marocain des agences digitales est saturé, bruyant et opaque. De beaux sites web masquent un travail médiocre. Les témoignages élogieux sont rarement vérifiés. Et le temps de vous en rendre compte, votre budget s'est envolé.",
        challengeBullet1Title: "Pas de comparaison indépendante",
        challengeBullet1Text: "Chaque agence se proclame '#1 au Maroc' sans aucune preuve.",
        challengeBullet2Title: "Des avis peu fiables",
        challengeBullet2Text: "Les témoignages sont sélectionnés au volet par les agences elles-mêmes.",
        challengeBullet3Title: "Absence de contexte local",
        challengeBullet3Text: "Les annuaires mondiaux ne comprennent pas les spécificités du marché marocain.",
        challengeQuote: "Nous avons épuisé deux agences et 200 000 dirhams avant de trouver un partenaire qui délivre de vrais résultats. Si cet annuaire avait existé, nous aurions gagné six mois.",
        challengeQuoteVerified: "Avis client vérifié",
        challengeQuoteScope: "Projet : SEO & Publicité Payante",
        approachLabel: "Notre Approche",
        approachTitle: "Une <span class='approach-focus-word'>meilleure façon</span> de <span class='approach-action-word'>choisir</span> votre agence.",
        approachDesc: "Nous faisons les recherches pour que vous puissiez décider sereinement.",
        approachPoint1Title: "Recherche Approfondie",
        approachPoint1Text: "Notre équipe éditoriale audite les portfolios, interroge de vrais clients et vérifie les registres du commerce de chaque agence avant son inscription.",
        approachPoint2Title: "Score Certifié",
        approachPoint2Text: "Chaque agence obtient un score indépendant basé sur 4 critères pondérés : avis, portfolio, présence sur le marché et étendue des services.",
        approachPoint3Title: "Contact Direct",
        approachPoint3Text: "Contactez les agences directement depuis leur profil. Sans commissions, sans intermédiaires, sans frais cachés. Juste une information honnête.",
        stat1Label: "Agences auditées et répertoriées",
        stat2Label: "Avis clients vérifiés par nos soins",
        stat3Label: "Villes marocaines couvertes",
        stat4Label: "Placements payants ou rangs sponsorisés",
        reviewsKicker: "Résultats clients vérifiés",
        reviewsTitle: "Ce que disent les équipes après avoir choisi via Agence Marketing Digital",
        reviewsDesc: "Des retours concrets d'équipes marocaines ayant utilisé les profils vérifiés, les notes d'audit et les preuves clients avant de contacter une agence.",
        reviewsMetric1: "Note vérifiée moyenne",
        reviewsMetric2: "Referaient une shortlist",
        reviewsMetric3: "Avis contrôlés",
        reviewsHired: "Agence",
        reviewsProject: "Projet",
        reviewsResult: "Résultat",
        review1Quote: "\"Le profil RMD montrait exactement ce dont nous avions besoin : preuves SEO, fourchette budgétaire et avis clients vérifiés. Nous les avons short-listés en une après-midi et les leads organiques ont progressé de 38% après les corrections.\"",
        review1Role: "Responsable marketing - Dakhla Travel Co.",
        review1Project: "Audit SEO technique et pages locales",
        review1Result: "Leads organiques +38% en 10 semaines",
        review2Quote: "\"Le profil de Pixagram a réduit le risque de décision. Les notes portfolio correspondaient à notre secteur, et leur équipe a reconstruit notre lancement social sans pousser de services inutiles.\"",
        review2Role: "Co-fondateur - Casa Homeware",
        review2Project: "Refonte de marque et lancement social commerce",
        review2Result: "Ventes Instagram +44% après lancement",
        review3Quote: "\"Nous avons comparé trois agences paid media et choisi MediaBoost parce que les preuves d'avis étaient précises. Leur nettoyage du tracking a enfin montré quelles campagnes produisaient des leads qualifiés.\"",
        review3Role: "Growth manager - Rabat Fintech Lab",
        review3Project: "Tracking acquisition payante et sprint CRO",
        review3Result: "Coût par lead qualifié réduit de 31%",
        picksLabel: "Sélection de l'Éditeur",
        picksTitle: "Les mieux notées ce mois-ci.",
        picksLink: "Notre evaluation",
        specialtiesLabel: "Spécialités",
        specialtiesTitle: "Trouvez votre besoin exact.",
        specialtiesLink: "Guides du blog",
        servicePaidAds: "Publicité Ads",
        serviceSocial: "Réseaux Sociaux",
        serviceWeb: "Conception Web",
        serviceBranding: "Image de Marque",
        serviceContent: "Marketing de Contenu",
        serviceGroupSearch: "Recherche & Croissance",
        serviceGroupBrand: "Marque & Social",
        serviceGroupWeb: "Web & Conversion",
        serviceGroupTopRanked: "Agences les mieux classées",
        serviceGroupStorytelling: "Stratégie de contenu",
        serviceGroupLaunchCampaigns: "Campagnes de lancement",
        serviceGroupGuides: "Guides de sélection",
        serviceGroupLandingPages: "Landing pages",
        serviceGroupEcommerce: "E-commerce",
        serviceGroupTechnicalSeo: "SEO technique",
        serviceGroupCRO: "Audits de conversion",
        serviceCompare: "Comparer les spécialistes",
        serviceSeoDesc: "Trouvez des agences pour audits techniques, SEO local, stratégie de contenu et croissance organique.",
        servicePaidAdsDesc: "Shortlistez des équipes pour Google Ads, Meta Ads, tracking et qualité des leads.",
        serviceSocialDesc: "Comparez créateurs, community managers et partenaires de campagne avec contexte marocain.",
        serviceWebDesc: "Évaluez des studios pour landing pages rapides, parcours de conversion, ecommerce et refontes.",
        serviceBrandingDesc: "Trouvez des partenaires pour positionnement, identité, concepts de campagne et messages de lancement.",
        serviceContentDesc: "Shortlistez des équipes pour calendriers éditoriaux, articles SEO, emails et autorité de marque.",
        trustLabel: "Indépendance",
        trustTitle: "Nous ne percevons aucun paiement pour modifier les classements.",
        trustDesc: "Nos classements sont éditoriaux et non commerciaux. Nous évaluons chaque agence selon la même méthodologie transparente, mise à jour trimestriellement sur la base de données de performance réelles.",
        trustPoint1: "Chaque avis est vérifié par email et recoupé manuellement",
        trustPoint2: "Audits de portfolio réalisés par des experts du secteur",
        trustPoint3: "Réévaluation trimestrielle de toutes les agences répertoriées",
        trustPoint4: "Aucune commission, frais de mise en relation ou lien sponsorisé",
        trustLink: "Lire notre méthodologie complète",
        guidesLabel: "Éditorial",
        guidesTitle: "Nos derniers guides et analyses.",
        guidesLink: "Tous les articles",
        badgeRanking: "Classement",
        badgeGuide: "Guide",
        badgeComparison: "Comparatif",
        guide1Title: "Audit SEO des agences au Maroc",
        guide1Desc: "Une shortlist technique fondee sur la sante de crawl, les Core Web Vitals, l indexation, les systemes de contenu et la croissance organique prouvee.",
        guide2Title: "Agences SEO a Casablanca : shortlist technique",
        guide2Desc: "Les equipes casablancaises qui montrent un vrai savoir-faire SEO : architecture propre, vitesse, local search et acquisition organique mesurable.",
        guide3Title: "Agences social media vues par le SEO",
        guide3Desc: "Comparaison des equipes social par demande de marque, cadence de contenu, decouvrabilite, pertinence createur et impact search.",
        guideDateJune: "Mis à jour en juin 2026",
        guideDateMay: "Mis à jour en mai 2026",
        guideDateApril: "Mis à jour en avril 2026",
        dirLabel: "Annuaire",
        dirTitle: "Agences Marketing Digital",
        dirDesc: "Explorez et comparez les agences par ville, service et niveau d'expertise.",
        showingTxt: "Affichage de",
        agenciesTxt: "agences",
        searchPlaceholder: "Nom de l'agence...",
        viewProfileBtn: "Voir le Profil",
        visitWebsiteBtn: "Visiter le Site",
        profileVisitWebsite: "Visiter le Site",
        profileContact: "Contact",
        profileAuditTitle: "télémétrie de l'audit technique",
        profileSpeed: "score pagespeed",
        profileVitals: "signaux web essentiels",
        profileCode: "indice de propreté du code",
        profileGoogleCWV: "Validé via Lighthouse API",
        profileAboutHeading: "Présentation",
        profileServicesHeading: "Services",
        profilePortfolioHeading: "Projets Marquants",
        profileWhyHeading: "Pourquoi",
        profileWhyHeadingEnd: "est Répertoriée",
        profileContactHeading: "Coordonnees Directes",
        profileSendMessageBtn: "Envoyer un Message",
        profileStatsHeading: "Chiffres Clés",
        profileStatFounded: "Création",
        profileStatTeam: "Collaborateurs",
        profileStatClients: "Clients Accompagnés",
        profileStatProject: "Budget Projet Moyen",
        profileStatBudget: "Budget Minimum",
        profileSimilarHeading: "Agences Similaires",
        rankBadgeLabel: "Classement 2026",
        rankTitle: "Top Agences de Marketing Digital au Maroc",
        rankDesc: "Après avoir évalué plus de 150 agences au Maroc, notre équipe indépendante a identifié les plus performantes selon des critères stricts de satisfaction client, de technicité et d'expertise sectorielle.",
        rankDate: "Mis à jour en juin 2026",
        rankVerified: "Méthodologie validée",
        rankTableTitle: "Aperçu Rapide",
        rankBottomTitle: "Comment nous choisissons ces agences",
        rankBottomDesc: "Notre méthodologie de classement est transparente et indépendante. Les placements payants ne sont pas acceptés. L'évaluation s'appuie sur quatre piliers :",
        rankCrit1: "1. Avis Clients Vérifiés",
        rankCrit1Desc: "Recueillis et authentifiés auprès de vrais clients, pondérés par la taille et la complexité du projet.",
        rankCrit2: "2. Qualité du Portfolio",
        rankCrit2Desc: "Notre équipe analyse les cas clients, l'exécution créative et les résultats mesurables obtenus.",
        rankCrit3: "3. Présence sur le Marché",
        rankCrit3Desc: "Années d'existence, taille de l'équipe, reconnaissance du secteur et publications de référence.",
        rankCrit4: "4. Diversité des Services",
        rankCrit4Desc: "Éventail des compétences offertes, niveau de spécialisation et synergie multicanale.",
        faqTitle: "Foire Aux Questions",
        faqRankQ1: "À quelle fréquence ces classements sont-ils mis à jour ?",
        faqRankA1: "Nos classements sont mis à jour trimestriellement. Nous collectons continuellement de nouveaux avis et réévaluons les portefeuilles des agences en Mars, Juin, Septembre et Décembre.",
        faqRankQ2: "Une agence peut-elle payer pour être mieux classée ?",
        faqRankA2: "Non. Nos classements sont 100% indépendants et fondés uniquement sur le mérite. L'achat de fonctionnalités de profil n'influence jamais la position d'une agence.",
        faqRankQ3: "Comment vérifiez-vous les avis clients ?",
        faqRankA3: "Nous authentifions chaque avis par validation de l'expéditeur, profil LinkedIn professionnel et contrôle des livrables. Les faux avis sont immédiatement supprimés.",
        faqRankQ4: "Quel budget prévoir pour travailler avec une agence du Top ?",
        faqRankA4: "Les agences du Top exigent généralement des abonnements mensuels à partir de 15 000 - 25 000 MAD. Pour un projet ponctuel (création de site), comptez minimum 50 000 MAD.",
        methTitle: "Nos Critères <span class='quiet'>d'Évaluation.</span>",
        methDesc: "Comment nous analysons, notons et classons les agences de marketing digital au Maroc. Mis à jour en juin 2026.",
        methFlowBtn: "Voir le processus",
        methFlowEyebrow: "01 / Processus de Validation",
        methFlowTitle: "Quatre étapes. Un seul standard.",
        methFlowDesc: "La même séquence est appliquée à chaque agence répertoriée, qu'elle ait postulé ou été découverte par notre équipe.",
        methStage1Tag1: "2+ ans",
        methStage1Tag2: "enregistrée",
        methStage1Tag3: "5+ projets",
        methStage2Tag1: "preuve de ROI",
        methStage2Tag2: "SEO",
        methStage2Tag3: "mobile",
        methStage3Tag1: "email",
        methStage3Tag2: "LinkedIn",
        methStage3Tag3: "téléphone",
        methStage4Tag1: "35%",
        methStage4Tag2: "30%",
        methStage4Tag3: "20%",
        methStage4Tag4: "15%",
        
        methEvidenceEyebrow: "02 / Carte des Preuves",
        methEvidenceTitle: "Les affirmations nécessitent des preuves.",
        methEvidenceLegalTitle: "Aspect Légal",
        methEvidenceLegalDesc: "L'enregistrement au Registre du Commerce, la continuité d'activité et la traçabilité des contacts sont contrôlés en premier.",
        methEvidenceWorkTitle: "Livrables",
        methEvidenceWorkDesc: "Les cas clients sont examinés sous l'angle des résultats réels, de la rigueur technique, du SEO et de l'optimisation mobile.",
        methEvidenceClientTitle: "Avis Clients",
        methEvidenceClientDesc: "Les avis sont rattachés à des identités réelles, et validés par entretien direct pour les budgets importants.",
        methEvidenceDataTitle: "Données",
        methEvidenceDataDesc: "Les scores sont pondérés de sorte qu'une marque bruyante ne puisse surclasser une agence plus performante.",
        
        methAfterEyebrow: "03 / Suivi Continu",
        methAfterTitle: "Nous contrôlons régulièrement les agences.",
        methAfterDesc: "Une agence classée peut monter, descendre ou être retirée si de nouvelles analyses indiquent une modification de sa qualité.",
        methAfterStep1Title: "Tous les 3 mois",
        methAfterStep1Desc: "Nous réévaluons les agences répertoriées pour éviter les données obsolètes.",
        methAfterStep2Title: "Signalements clients",
        methAfterStep2Desc: "Les plaintes fondées de clients vérifiés déclenchent un audit manuel.",
        methAfterStep3Title: "Preuves périmées",
        methAfterStep3Desc: "Un portfolio inactif, des litiges légaux ou des déclarations infondées font baisser la note.",
        methAfterStep4Title: "Faux avis",
        methAfterStep4Desc: "Toute tentative de manipulation entraîne le retrait immédiat du classement.",
        methOverviewHeading: "Présentation générale",
        methOverviewP1: "Notre processus de notation est conçu pour être objectif et transparent. Toutes les agences subissent le même protocole d'audit, qu'elles se soient inscrites d'elles-mêmes ou identifiées par nos soins.",
        methOverviewP2: "L'audit complet prend 2 à 4 semaines et passe par quatre étapes : présélection administrative, audit de portfolio, vérification client directe, puis notation finale.",
        methStep1Title: "1. Présélection Administrative",
        methStep1Desc: "Nous validons l'éligibilité de l'agence sur des critères minimaux :",
        methStep1Bullet1: "Minimum 2 années d'existence continue",
        methStep1Bullet2: "Site web fonctionnel décrivant clairement l'offre",
        methStep1Bullet3: "Enregistrement légal au Registre du Commerce au Maroc",
        methStep1Bullet4: "Portfolio présentant au moins 5 réalisations concrètes",
        methStep2Title: "2. Audit de Portfolio",
        methStep2Desc: "Nos auditeurs décortiquent les cas clients présentés par l'agence :",
        methStep2Bullet1: "Qualité technique et originalité créative des livrables",
        methStep2Bullet2: "Preuves de résultats chiffrés (ROI, conversion, trafic)",
        methStep2Bullet3: "Performance des intégrations web (vitesse, SEO, mobile)",
        methStep3Title: "3. Enquête Client Directe",
        methStep3Desc: "C'est l'étape déterminante. Nous vérifions l'expérience vécue par les clients :",
        methStep3Bullet1: "Contrôle d'identité des signataires des avis",
        methStep3Bullet2: "Recoupement des profils LinkedIn des directeurs de projet client",
        methStep3Bullet3: "Entretiens téléphoniques pour les projets de plus de 50 000 MAD",
        methStep4Title: "4. Notation Composite",
        methStep4Desc: "Les agences retenues reçoivent une note globale indexant quatre piliers :",
        methCrit1: "Avis Clients Authentifiés",
        methCrit2: "Qualité du Portfolio",
        methCrit3: "Présence sur le Marché",
        methCrit4: "Éventail des Compétences",
        contactTitle: "Contactez Agence Marketing Digital",
        contactDesc: "Une question sur nos donnees, une correction, une demande d ajout ou une recherche editoriale ? Envoyez les details a notre equipe.",
        contactFormHeading: "Envoyer un message",
        contactFirstName: "Prénom",
        contactLastName: "Nom",
        contactEmail: "Email",
        contactSubject: "Sujet",
        contactMessage: "Message",
        contactSubmitBtn: "Envoyer le Message",
        holderFirstName: "Votre prénom",
        holderLastName: "Votre nom de famille",
        holderEmail: "nom@entreprise.ma",
        holderMessage: "Comment pouvons-nous vous aider ?",
        contactExploreEyebrow: "Vous préférez explorer d'abord ?",
        contactExploreTitle: "Lisez les recherches avant d'envoyer un message.",
        contactExploreDesc: "Utilisez le blog et la methodologie pour le contexte. Gardez le formulaire pour les corrections, demandes d'ajout et questions directes.",
        contactExploreDirectory: "Lire le blog",
        contactExploreRankings: "Voir la methodologie",
        subjectOption1: "Demande d'information générale",
        subjectOption2: "Inscrire mon agence dans l'annuaire",
        subjectOption3: "Signaler une anomalie",
        subjectOption4: "Opportunité de partenariat",
        contactPathListingTitle: "Étude d'inscription agence",
        contactPathListingText: "Envoyez le nom de l'agence, le site, la ville, les services et 2-3 références clients pour aider notre équipe à évaluer le profil.",
        contactPathCorrectionTitle: "Correction de données",
        contactPathCorrectionText: "Signalez une note obsolète, un mauvais service, une coordonnée incorrecte ou une affirmation portfolio. Ajoutez l'URL du profil si possible.",
        contactPathBuyerTitle: "Aide à la shortlist",
        contactPathBuyerText: "Indiquez votre ville, budget, calendrier et services recherches. Nous vous orienterons vers la recherche ou le guide le plus pertinent.",
        contactResponseTitle: "Ce qui se passe ensuite",
        contactResponse1: "Les demandes éditoriales sont vérifiées avant toute modification de profil.",
        contactResponse2: "Les demandes d'inscription doivent contenir des preuves, pas seulement des arguments commerciaux.",
        contactResponse3: "Les messages les plus utiles incluent liens, chiffres et contexte projet.",
        contactInfoTitle: "Coordonnées de Contact",
        contactOfficeTitle: "Siège Social",
        officeCity: "Casablanca, Maroc",
        footerDesc: "Recherche independante sur les agences de marketing digital au Maroc. Avis objectifs, guides pratiques et aucune influence payante.",
        footerExploreHeading: "Explorer",
        footerResourcesHeading: "Ressources",
        footerDirHeading: "Annuaire",
        footerLinkAll: "Toutes les agences",
        footerLinkCity: "Par ville",
        footerLinkService: "Par service",
        footerCitiesHeading: "Villes",
        footerCompanyHeading: "Société",
        footerLegalHeading: "Légal",
        footerLinkPrivacy: "Confidentialité",
        footerLinkTerms: "Conditions d'utilisation",
        palettePlaceholder: "Rechercher agences, pages, villes...",
        blogTitle: "Analyse SEO des agences",
        blogLede: "Notes techniques sur les agences marocaines, la visibilite organique, la qualite de crawl, les Core Web Vitals, la profondeur editoriale et les preuves reelles d acquisition SEO.",
        navBlog: "blog",
        aboutEyebrow: "A propos",
        aboutTitle: "Recherche agence <span class='quiet'>independante.</span>",
        aboutLead: "Agence Marketing Digital aide les equipes marocaines a comprendre le marche des agences avec des standards editoriaux clairs, des guides pratiques et des notes de recherche transparentes.",
        aboutMissionTitle: "Ce que nous faisons",
        aboutMissionText: "Nous analysons les affirmations des agences, expliquons les criteres de selection et publions des conseils utiles pour poser les bonnes questions avant de choisir un partenaire.",
        aboutIndependenceTitle: "Notre independance",
        aboutIndependenceText: "Le processus editorial est separe des demandes commerciales. Nous ne vendons pas de positions, et les corrections sont examinees avec des preuves avant publication.",
        aboutAudienceTitle: "Pour qui",
        aboutAudienceText: "Le site s adresse aux fondateurs, responsables marketing et operations qui veulent evaluer plus sereinement les partenaires SEO, paid media, social, web et contenu au Maroc.",
        aboutCtaEyebrow: "Processus & Inscription",
        aboutCtaTitle: "Vous voulez comprendre notre processus ?",
        aboutCtaText: "Consultez la methodologie pour voir les criteres de recherche, ou contactez l equipe editoriale pour une correction ou une demande d ajout.",
        aboutMethodologyCta: "Lire la methodologie",
        aboutContactCta: "Nous contacter",
        backToInsights: "retour aux analyses",
        readTime: "min de lecture",
        postedLabel: "le",
        authorLabel: "par",
        navCharter: "Charte Éditoriale",
        charterTitle: "Charte Éditoriale & Standards d'Évaluation",
        charterSubtitle: "standards de l'annuaire & signaux de confiance",
        charterDesc: "Les standards publics de notre annuaire : présentation des données agences, signaux de confiance, états de vérification et preuves de classement.",
        charterSec1: "01 · tokens de couleur (système oklch)",
        charterSec2: "02 · familles typographiques & échelle",
        charterSec3: "03 · valeurs d'espacement",
        charterSec4: "04 · composants d'interface",
        charterSec5: "05 · spécifications des cartes de l'annuaire",
        swatchBrandTitle: "cobalt électrique",
        swatchBrandDesc: "Couleur d'accentuation principale, boutons, tags mis en évidence, badges de rang, soulignement au survol.",
        swatchPaperTitle: "fond papier base",
        swatchPaperDesc: "Arrière-plan principal de la page. Blanc cassé propre teinté de gris frais.",
        swatchCardTitle: "fond carte papier",
        swatchCardDesc: "Arrière-plan des cartes, menus déroulants en ligne, arrière-plan de la barre de navigation.",
        swatchGraphiteTitle: "graphite foncé",
        swatchGraphiteDesc: "Bandes sombres à fort contraste, panneaux de statistiques, boutons d'appel à l'action, widgets de pied de page.",
        swatchInkTitle: "encre primaire",
        swatchInkDesc: "Titres, en-têtes, détails d'interface à fort contraste, numéros de rang de cartes.",
        swatchMutedTitle: "encre atténuée",
        swatchMutedDesc: "Corps de texte, étiquettes de description standard, espaces réservés de recherche.",
        swatchSuccessTitle: "succès d'audit",
        swatchSuccessDesc: "Badges de statut verts diagnostiques, indicateurs pulsants, validations d'audit de performance.",
        swatchBorderTitle: "filet de séparation",
        swatchBorderDesc: "Diviseurs nets, grilles de mise en page fines, bordures de panneaux.",
        typeDisplayTitle: "Titre Display (Space Grotesk Gras)",
        typeH1Title: "En-tête H1 (Space Grotesk)",
        typeH2Title: "Titre de Section H2 (Space Grotesk)",
        typeH3Title: "Titre de Carte H3 (Space Grotesk)",
        typeBodyTitle: "Texte Courant (Inter)",
        typeMonoTitle: "Code Monospace (JetBrains Mono)",
        compButtonsTitle: "boutons & micro badges",
        compTerminalTitle: "simulateur de terminal",
        compBrandingTitle: "mot-symbole de marque",
        compBrandingDesc: "Un mot-symbole typographique avec contraste de graisse et accent cobalt sur Marketing.",
        compBtnPrimary: "bouton principal",
        compBtnSoft: "bouton contour",
        compBadgeVerified: "statut vérifié",
        compBadgeRating: "note avis",
        compBadgeRank: "badge de rang",
        compBadgeTag: "tag vedette",
        cardSpecTitle: "Spécification de Carte",
        cardSpecDesc: "Modèle visuel illustrant l'alignement, la disposition des boutons, les badges de certification et la notation.",
        ctaMatchmaker: "Trouver mon agence",
        editorialHeading: "Analyses Éditoriales",
        dirLabel: "Annuaire",
        dirTitle: "Agences de Marketing Digital",
        dirDesc: "Parcourez et comparez les agences par ville, service et expertise.",
        rankBadgeLabel: "Classement 2026",
        rankTitle: "Meilleures Agences de Marketing Digital au Maroc",
        rankDesc: "Après avoir évalué plus de 150 agences au Maroc, notre équipe a identifié les meilleures sur la base d'avis vérifiés, de la qualité du portfolio, de la présence sur le marché et de l'expertise.",
        footerCitiesHeading: "Villes",
        footerResourcesHeading: "Ressources",
        footerLegalHeading: "Légal",
        showingTxt: "Affichage",
        agenciesTxt: "agences",
        viewProfileBtn: "Voir le Profil",
        searchPlaceholder: "Nom de l'agence...",
        backToInsights: "retour aux articles",
        matchmakerStep1: "Quel service recherchez-vous ?",
        matchmakerStep2: "Dans quelle ville êtes-vous ?",
        matchmakerStep3: "Quel est votre budget mensuel ?",
        matchmakerStep4: "Décrivez votre projet"
    }
};

// Central Editorial/Blog Database
const ARTICLE_DATA = [
    {
        id: "top-agencies",
        date: "12 Jun 2026",
        readTimeEN: "8 min read",
        readTimeFR: "8 min de lecture",
        author: "Karim El Amrani",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop",
        en: {
            badge: "SEO Audit",
            title: "Morocco SEO Agency Audit: Top Performers",
            desc: "A technical shortlist based on crawl health, Core Web Vitals, indexation discipline, content systems, and proof of search-led growth.",
            content: `
                <p>Selecting the right digital marketing agency in Morocco is a crucial strategic step for growing your organic visibility. With hundreds of self-proclaimed specialists in Casablanca, Rabat, and Tangier, we have crawled and audited the technical setups of major agencies to bring you a factual ranking.</p>
                <p>Our audit methodology focuses heavily on raw performance parameters (PageSpeed, correct indexing, and Core Web Vitals) alongside client retention history. Below is our verified list, showcasing the absolute top choices for performance-led and branding-centric marketing.</p>
                <h2>making the final decision</h2>
                <p>If your goals are purely transactional, technical search optimization, and scaling PPC pipelines, we highly recommend working with <strong>RMD</strong>. If you are looking to run social-first campaigns and establish creative brand positioning, <strong>Pixagram</strong> is the ideal choice. Make sure to consult our ranking methodology details to verify how we compile these comparison cards.</p>
            `,
            embeddedListings: [
                { rank: 1, name: "RMD", badge: "SEO Leader (Score: 98/100)", desc: "<strong>Why RMD is ranked #1:</strong> they represent the gold standard in technical SEO and performance. While other agencies focus on vanity reports and animations, RMD focuses on clean crawls, search intent alignment, and high-performance search advertising campaigns.", linkText: "visit rmd website →", id: "rmd" },
                { rank: 2, name: "Pixagram", badge: "Branding Leader (Score: 95/100)", desc: "<strong>Why Pixagram is ranked #2:</strong> pixagram bridges the gap between branding and acquisition. Their social advertising and content frameworks are highly engaging, delivering incredible conversion loops.", linkText: "visit pixagram website →", id: "pixagram" }
            ]
        },
        fr: {
            badge: "Classement",
            title: "Top Agences de Marketing Digital au Maroc",
            desc: "Notre classement définitif des meilleures agences basé sur les avis vérifiés et les métriques de performance.",
            content: `
                <p>Choisir la bonne agence de marketing digital au Maroc est une étape stratégique déterminante pour votre visibilité organique. Avec plusieurs centaines de prestataires sur le marché, nous avons audité techniquement et passé au crible les portefeuilles d'agences afin de vous livrer un comparatif factuel.</p>
                <p>Notre méthodologie se concentre sur les performances réelles (Core Web Vitals, conformité d'indexation, audits de vitesse) et l'analyse de l'acquisition client. Voici notre classement des meilleures agences.</p>
                <h2>prendre la décision finale</h2>
                <p>Si vos objectifs sont orientés sur le trafic organique pur, l’optimisation technique ou les campagnes payantes (SEA), l’agence <strong>RMD</strong> l’emporte de loin. Si vous souhaitez axer votre stratégie sur la notoriété, le design et les réseaux sociaux, <strong>Pixagram</strong> saura répondre à vos besoins créatifs.</p>
            `,
            embeddedListings: [
                { rank: 1, name: "RMD", badge: "Leader SEO (Score : 98/100)", desc: "<strong>Pourquoi RMD est classée #1 :</strong> ils représentent la référence absolue en matière de SEO technique et de performance globale. RMD se concentre sur le code propre, l'intention de recherche et les campagnes SEA performantes.", linkText: "voir le site de rmd →", id: "rmd" },
                { rank: 2, name: "Pixagram", badge: "Leader Branding (Score : 95/100)", desc: "<strong>Pourquoi Pixagram est classée #2 :</strong> Pixagram fait la transition parfaite entre image de marque et acquisition. Leurs tunnels de vente sociaux et créations visuelles sont exceptionnellement engageants.", linkText: "voir le site de pixagram →", id: "pixagram" }
            ]
        }
    },
    {
        id: "seo-casablanca",
        date: "08 May 2026",
        readTimeEN: "6 min read",
        readTimeFR: "6 min de lecture",
        author: "Omar Fassi",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop",
        en: {
            badge: "Technical SEO",
            title: "Casablanca SEO Agencies: Technical Shortlist",
            desc: "Which Casablanca teams show real SEO craft: fast builds, clean architecture, local search coverage, and measurable organic acquisition.",
            content: `
                <p>Casablanca is the economic heartbeat of Morocco, and search visibility is highly competitive. Ranking on page one for high-intent keywords can make or break your customer acquisition strategy. Unfortunately, many local agencies pitch premium SEO services but execute outdated, spammy tactics that risk Google penalties.</p>
                <p>Our research team has analyzed the portfolios of 30+ agencies operating in Casablanca to determine who actually ranks clients using modern white-hat techniques. We looked at technical audit depth, link velocity, and local SEO optimizations.</p>
                <h2>avoiding elementor and visual builder drift</h2>
                <p>A critical finding from our audits is that many agencies build client websites using bloated visual builders. This degrades Core Web Vitals, slowing down rankings. True SEO leaders build fast, lightweight codebases that give your site a competitive edge.</p>
            `,
            embeddedListings: [
                { rank: 4, name: "DigitalWave", badge: "Web Dev & SEO (Score: 89/100)", desc: "<strong>Why DigitalWave is featured:</strong> based in Casablanca, they are custom web engineering specialists. They design sites from day one with search indexing and mobile responsiveness in mind, ensuring flawless technical SEO performance.", linkText: "visit digitalwave website →", id: "digitalwave" }
            ]
        },
        fr: {
            badge: "Guide",
            title: "Meilleures Agences SEO à Casablanca",
            desc: "Une sélection rigoureuse d'experts en référencement naturel pour booster votre positionnement.",
            content: `
                <p>Casablanca est le poumon économique du Maroc, et la concurrence sur les moteurs de recherche y est féroce. Apparaître en première page peut radicalement changer votre acquisition client. Malheureusement, de nombreuses agences locales vendent des abonnements SEO sans livrer de résultats mesurables.</p>
                <p>Notre équipe a analysé les réalisations de plus de 30 agences basées à Casablanca. Nous avons évalué la qualité de leur SEO technique, la vitesse d'indexation et l'optimisation locale (Google Maps).</p>
                <h2>les dangers de la surcharge technique (bloat)</h2>
                <p>Un constat récurrent de nos audits : l'usage abusif d'éditeurs visuels lourds qui détériorent les signaux web essentiels (Core Web Vitals). Les leaders du SEO développent des sites web légers et performants pour offrir un avantage technique décisif.</p>
            `,
            embeddedListings: [
                { rank: 4, name: "DigitalWave", badge: "Dév & SEO (Score : 89/100)", desc: "<strong>Pourquoi DigitalWave est recommandée :</strong> implantés à Casablanca, ils allient ingénierie web sur mesure et optimisation sémantique. Leurs architectures de code propre garantissent des indexations extrêmement rapides.", linkText: "voir le site de digitalwave →", id: "digitalwave" }
            ]
        }
    },
    {
        id: "social-media-compared",
        date: "15 Apr 2026",
        readTimeEN: "10 min read",
        readTimeFR: "10 min de lecture",
        author: "Laila Bennani",
        image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=400&fit=crop",
        en: {
            badge: "Search Signals",
            title: "Social Agencies Through an SEO Lens",
            desc: "A comparison of social teams by brand demand, content velocity, discoverability, creator relevance, and downstream search impact.",
            content: `
                <p>Social media marketing in Morocco requires a deep understanding of local dialects (Darija), cultural micro-trends, and platform shifts. TikTok and Instagram are driving massive consumer decisions, yet many corporate campaigns feel out-of-touch and yield low engagement rates.</p>
                <p>We compared the top social media management agencies in Morocco across content creativity, community responsiveness, influencer relationship access, and paid campaign management capability.</p>
                <h2>creative storytelling vs. generic posts</h2>
                <p>An agency that simply schedules calendar posts is a waste of resource. Ambitious brands need content creators who can script short-form videos, capitalize on trends, and establish authentic brand affinity.</p>
            `,
            embeddedListings: [
                { rank: 2, name: "Pixagram", badge: "Social & Creative (Score: 95/100)", desc: "<strong>Why Pixagram is a top choice:</strong> they are the premier brand storytelling agency in Casablanca. They excel at building viral social media formats, executing creator collaborations, and driving high-converting social campaigns.", linkText: "visit pixagram website →", id: "pixagram" },
                { rank: 6, name: "Sahara Digital", badge: "Agadir Regional Leader (Score: 88/100)", desc: "<strong>Why Sahara Digital is listed:</strong> they are the primary digital marketing agency in Southern Morocco. They lead social campaign executions for Agadir's hospitality and tourism sectors.", linkText: "visit saharadigital website →", id: "saharadigital" }
            ]
        },
        fr: {
            badge: "Comparatif",
            title: "Comparatif des Agences Social Media",
            desc: "Analyse comparative des meilleures agences de gestion de réseaux sociaux au Maroc.",
            content: `
                <p>La communication sur les réseaux sociaux au Maroc exige une maîtrise parfaite des codes culturels, de la Darija et des nouvelles tendances de plateformes. Instagram et TikTok orientent la majorité des choix de consommation.</p>
                <p>Nous avons comparé les meilleures agences social media au Maroc selon la créativité du contenu, la réactivité communautaire, et la gestion des campagnes d'acquisition payante (Social Ads).</p>
                <h2>storytelling vs. posts génériques</h2>
                <p>Une agence qui se limite à publier un calendrier pré-établi ne suffit plus. Les marques ont besoin de concepteurs-rédacteurs capables de scénariser du contenu vidéo court et d'engager sincèrement leur communauté.</p>
            `,
            embeddedListings: [
                { rank: 2, name: "Pixagram", badge: "Social & Création (Score : 95/100)", desc: "<strong>Pourquoi Pixagram est incontournable :</strong> basée à Casablanca, c'est l'agence de référence pour le storytelling visuel et les activations de créateurs. Leurs formats vidéo Darija convertissent fortement.", linkText: "voir le site de pixagram →", id: "pixagram" },
                { rank: 6, name: "Sahara Digital", badge: "Leader Régional Souss (Score : 88/100)", desc: "<strong>Pourquoi Sahara Digital est listée :</strong> agence de référence à Agadir, elle anime avec succès la communication des riads, resorts et projets d'écotourisme du Sud Marocain.", linkText: "voir le site de saharadigital →", id: "saharadigital" }
            ]
        }
    }
];
